name: Swift Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: mxcl/Xcodebuild
        uses: mxcl/xcodebuild@v3.0.0
        with:
          action: test # optional, default is test
          code-coverage: true # optional, default is false
          configuration: Debug
          scheme: All Tests
